Update index.html
Previously  we tried to access the hashmap values , however its giving an error Uncaught TypeError: map1.get is not a function as .map() method work on array, In your case you first need to check values are in array([]) form with Array.isArray(values), If it's result true it means it's in array form then you can use .map() or if it's false then make sure calling function pass it in array form.so we try to put in an array form .